'use strict';
// mock-run.js — org-nft-flows against a fake RPC + fake GitHub. Proves: cursor bootstrap from ledger coverage, watch-set
// match, raw-before-ledger, merge by recordKey (no duplicates on a second run), index coverage, cursor written last.
const http = require('http'); const zlib = require('zlib'); const { spawn } = require('child_process'); const fs = require('fs'); const path = require('path');
const PL = 'terra17z7fpaa8kah698xn5tarrcucvualdy4wsztkfc404g3garucpu6qmxp50g', PLV = 'terra127dehd2d6t7ynnezkxkre2w83ze0t7lmghpu6vn4y5mfmwfj5x9qqdh4sz', BBL = 'terra1ej4cv98e9g2zjefr5auf2nwtq4xl3dm7x0qml58yna2ml2hk595s7gccs9';
const NC = process.env.NC || path.join(__dirname, '../../../nft-collections'); const venues = JSON.parse(fs.readFileSync(path.join(NC, 'venues.json'), 'utf8')); const plc = JSON.parse(fs.readFileSync(path.join(NC, 'pixel-lions/collection.json'), 'utf8'));
const files = {}; // fake tla-core
const put = (p, obj) => { files[p] = p.endsWith('.gz') ? zlib.gzipSync(Buffer.from(JSON.stringify(obj))) : Buffer.from(JSON.stringify(obj)); };
put('venues.json', venues); put('pixel-lions/collection.json', plc);
put('pixel-lions/ledger/index.json', { collection: 'pixel-lions', total: 0, by_kind: {}, months: [], coverage: [{ source: 'pixel-lions/raw:1-1000', from: 1, to: 1000 }], known_gaps: [] });
const ev = (c, o) => ({ type: 'wasm', attributes: Object.entries(Object.assign({ _contract_address: c }, o)).map(([k, v]) => ({ key: k, value: String(v) })) });
const blocks = {}; const results = {}; let HEAD = 1020;
blocks[1003] = { txs: ['dHgx'] }; results[1003] = [{ code: 0, events: [ev(PL, { action: 'send_nft', sender: 'terra1me', recipient: PLV, token_id: 42 }), ev(PLV, { action: 'stake', from: 'terra1me', token_id: 42 })] }];
blocks[1007] = { txs: ['dHgy', 'dHgz'] }; results[1007] = [{ code: 0, events: [ev(BBL, { action: 'deposit', amount: 5000000, from: 'terra1w2', token: 'terra1bluna' })] }, { code: 0, events: [ev('terra1unrelated', { action: 'swap' })] }];
const gh = []; const ghs = http.createServer((req, res) => { let b = ''; req.on('data', c => b += c); req.on('end', () => { const m = req.url.match(/\/contents\/([^?]+)/); const p = m && decodeURIComponent(m[1]); gh.push(req.method + ' ' + p);
  if (req.method === 'GET') { if (!files[p]) { res.statusCode = 404; return res.end('{}'); } if ((req.headers.accept || '').includes('raw')) return res.end(files[p]); return res.end(JSON.stringify({ sha: 'sha-' + p, size: files[p].length })); }
  const body = JSON.parse(b); files[p] = Buffer.from(body.content, 'base64'); res.end('{}'); }); });
const LUNA_HITS = []; const LUNA_DAILY = { '2026-09-13': 0.05 };   // 1.1.3: mutable — a day "arrives" mid-gate   // 1.1.2: the exact path the cron asks for — the 404 of 2026-09-13 was a right suffix on the wrong repo
// 1.2.0: the fake tla-core serves a token-catalog (LUNA is native; bLUNA + USDC by their real denoms) and a bluna-usd-daily series
const CATALOG = { tokens: [{ denom: 'terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml', effective: { symbol: 'bLUNA', decimals: 6 } }, { denom: 'ibc/2C962DAB9F57FE0921435426AE75196009FAA1981BF86991203C8411F8980FDB', effective: { symbol: 'USDC', decimals: 6 } }, { denom: 'terra1bluna', discovered: { symbol: 'TESTLST', decimals: 6 } }] };
const BLUNA_DAILY = { '2026-09-12': 0.08 };
// 1.3.0: the fake tla-core serves price-history/YYYY/MM.json — THE org oracle — assembled from the mutable day maps above
const ORACLE_HITS = [];
function oracleMonth(mk) { const days = {}; const add = (m, sym) => { for (const [d, usd] of Object.entries(m)) if (d.slice(0, 7).replace('-', '/') === mk) (days[d] = days[d] || {})[sym] = { usd, src: sym === 'bLUNA' && d < '2025-09-11' ? 'LUNA×ratio(interpolated)' : 'coingecko' }; }; add(LUNA_DAILY, 'LUNA'); add(BLUNA_DAILY, 'bLUNA'); for (const d of Object.keys(days)) days[d].USDC = { usd: 1.0001, src: 'coingecko' }; return { meta: { module: 'price-history' }, days }; }
const rpc = http.createServer((req, res) => { const u = new URL('http://x' + req.url); if (u.pathname.endsWith('token-catalog/snapshots/current.json')) return res.end(JSON.stringify(CATALOG)); { const m = /price-history\/(\d{4}\/\d{2})\.json$/.exec(u.pathname); if (m) { ORACLE_HITS.push(u.pathname); const doc = oracleMonth(m[1]); return res.end(JSON.stringify(doc)); } } /* an oracle month is always a file (possibly with no days yet) */ if (u.pathname.endsWith('bluna-usd-daily.json') || u.pathname.endsWith('luna-usd-daily.json')) { LUNA_HITS.push(u.pathname); res.statusCode = 404; return res.end('{}'); } if (u.pathname === '/status') return res.end(JSON.stringify({ result: { sync_info: { latest_block_height: String(HEAD) } } })); const h = Number(u.searchParams.get('height')); if (u.pathname === '/block') return res.end(JSON.stringify({ result: { block: { header: { time: '2026-09-13T01:00:00Z' }, data: { txs: (blocks[h] || {}).txs || [] } } } })); if (u.pathname === '/block_results') return res.end(JSON.stringify({ result: { txs_results: results[h] || [] } })); res.end('{}'); });
(async () => {
  await new Promise(r => ghs.listen(0, r)); await new Promise(r => rpc.listen(0, r));
  const env = Object.assign({}, process.env, { GITHUB_TOKEN: 'x', COLLECTION: 'pixel-lions', TLA_CORE_RAW: 'http://127.0.0.1:' + rpc.address().port + '/', NFTC_RAW: 'http://127.0.0.1:' + rpc.address().port + '/nftc/', GITHUB_API: 'http://127.0.0.1:' + ghs.address().port, RPC_PRIMARY: 'http://127.0.0.1:' + rpc.address().port, RPC_FALLBACK: 'http://127.0.0.1:' + rpc.address().port, PACE_MS: '1', HEAD_LAG: '0' });
  let pass = 0, fail = 0; const ok = (c, m, d) => { if (c) { pass++; console.log('  ✓', m); } else { fail++; console.log('  ✗', m, d === undefined ? '' : '\n      got: ' + JSON.stringify(d).slice(0, 1200)); } };   // 1.5.1: a failing assertion prints what it saw
  const run = () => new Promise(res => { let out = ''; const p = spawn('node', ['--max-old-space-size=200', path.join(__dirname, 'index.js')], { env }); /* 1.2.1: the heap cap is part of the gate (Render ~256 MB) */ p.stdout.on('data', d => { out += d; }); p.stderr.on('data', d => { out += d; }); p.on('exit', (code, signal) => res({ status: code, signal, stdout: out })); });   // async: the fake servers live in THIS process
  const r1 = await run(); console.log(r1.stdout.split('\n').filter(l => /cursor|walked|done|FATAL/.test(l)).join('\n'));
  const J = (p) => JSON.parse(p.endsWith('.gz') ? zlib.gunzipSync(files[p]) : files[p]);
  ok(/cursor bootstrapped from pixel-lions ledger coverage: 1000/.test(r1.stdout), 'cursor bootstrapped from THIS collection\'s ledger coverage');
  ok(files['pixel-lions/raw/forward/2026-09-13.json.gz'] && J('pixel-lions/raw/forward/2026-09-13.json.gz').some(t => t.h === 1003) && J('pixel-lions/raw/forward/2026-09-13.json.gz').some(t => t.h === 1007), 'raw day file for pixel holds the stake tx + the venue-only BBL tx (archived under every collection on that venue)');
  const led = J('pixel-lions/ledger/2026/09.json'); ok(led.length >= 2 && led.some(r => r.kind === 'stake' && r.token_id === '42') && led.some(r => r.kind === 'venue_deposit'), 'ledger month: stake #42 + the BBL deposit (venue-level, copied to collections on BBL)');
  ok(!Object.keys(files).some(k => k.startsWith('adao/') || k.startsWith('tla-locks/')), 'nothing written outside pixel-lions/ (one service, one folder)');
  const ix = J('pixel-lions/ledger/index.json'); ok(ix.coverage.some(c => c.source === 'forward:org-nft-flows' && c.from === 1001 && c.to === 1020) && ix.total === led.length, 'index: forward coverage 1001→1020, total = records');
  ok(J('pixel-lions/ledger/cursor.json').height === 1020, 'cursor → 1020');
  const order = gh.filter(x => x.startsWith('PUT')).map(x => x.slice(4)); ok(order.indexOf('pixel-lions/raw/forward/2026-09-13.json.gz') < order.indexOf('pixel-lions/ledger/2026/09.json') && order.indexOf('pixel-lions/ledger/cursor.json') > order.lastIndexOf('pixel-lions/ledger/index.json'), 'write order: raw → ledger → index → cursor');
  const hb = J('pixel-lions/nft-flows/heartbeat.json'); ok(hb.status === 'ok' && hb.matched === 2 && hb.cron === 'org-nft-flows-pixel-lions', 'heartbeat ok, matched 2 (unrelated swap ignored), cron named per collection');
  const r2 = await run(); ok(r2.status === 0 && /nothing new/.test(r2.stdout), 'second run: nothing new, exits clean'); ok(J('pixel-lions/ledger/2026/09.json').length === led.length, 'ledger unchanged on re-run');
  // 1.1.1 regression — the 2026-09-13 tla-locks failure: a SECOND match on the same UTC day makes the cron READ the
  // existing raw/forward/<day>.json.gz through the raw media type; bodies must arrive as bytes (utf8-mangled gzip →
  // 'incorrect header check', every run failed, cursor frozen at 08:45 while the heartbeat stayed fresh).
  // 1.5.0: a real protobuf tx in the block — a DAODAO unstake whose token ids live only in the body — must arrive on the raw
  // record as `m` (FCD `messages` shape) and classify with the ids; the fake 'dHg0' bytes beside it decode to nothing and stay body-less.
  const pb = { vi: (n) => { const o = []; let x = BigInt(n); do { let b = Number(x & 0x7fn); x >>= 7n; if (x) b |= 0x80; o.push(b); } while (x); return Buffer.from(o); }, ld: (f, buf) => Buffer.concat([pb.vi((f << 3) | 2), pb.vi(buf.length), buf]) };
  const execMsg = pb.ld(1, Buffer.from('terra1you')).length ? Buffer.concat([pb.ld(1, Buffer.from('terra1you')), pb.ld(2, Buffer.from(PLV)), pb.ld(3, Buffer.from(JSON.stringify({ unstake: { token_ids: ['501', '502'] } })))]) : null;
  const anyMsg = Buffer.concat([pb.ld(1, Buffer.from('/cosmwasm.wasm.v1.MsgExecuteContract')), pb.ld(2, execMsg)]);
  const txBytes = Buffer.concat([pb.ld(1, pb.ld(1, anyMsg)), pb.ld(2, Buffer.from([]))]).toString('base64');   // Tx{ body{ messages[any] }, auth_info{} }
  HEAD = 1030; blocks[1025] = { txs: ['dHg0', txBytes] }; results[1025] = [{ code: 0, events: [ev(PL, { action: 'send_nft', sender: 'terra1you', recipient: PLV, token_id: 77 }), ev(PLV, { action: 'stake', from: 'terra1you', token_id: 77 })] }, { code: 0, events: [ev(PLV, { action: 'unstake', from: 'terra1you', claim_duration: '604800' })] }];
  const r3 = await run(); ok(r3.status === 0 && !/incorrect header check|FATAL/.test(r3.stdout), 'third run (same-day 2nd match): reads the existing gz part cleanly, no FATAL', r3.stdout.split('\n').filter(l => /FATAL|header/.test(l)).join(' | '));
  const part = J('pixel-lions/raw/forward/2026-09-13.json.gz'); ok(part.length === 4 && part.some(t => t.h === 1025) && part.some(t => t.h === 1003), 'gz part merged: 4 txs (prior 2 kept + 2 new)', part.map(t => t.h));
  ok(J('pixel-lions/ledger/2026/09.json').some(r => r.token_id === '77'), 'ledger gained the new stake #77'); ok(J('pixel-lions/ledger/cursor.json').height === 1030, 'cursor → 1030');
  { const withBody = part.filter(t => t.h === 1025 && t.m), without = part.filter(t => t.h === 1025 && !t.m);
    ok(withBody.length === 1 && without.length === 1 && withBody[0].m[0]['@type'] === '/cosmwasm.wasm.v1.MsgExecuteContract' && withBody[0].m[0].contract === PLV && withBody[0].m[0].msg.unstake.token_ids.join() === '501,502', '1.5.0: the protobuf tx is archived with `m` (decoded MsgExecuteContract, FCD shape); the undecodable bytes stay body-less', part.filter(t => t.h === 1025).map(t => t.m));
    const un = J('pixel-lions/ledger/2026/09.json').filter(r => r.kind === 'unstake'); ok(un.length === 2 && un.map(r => r.token_id).join() === '501,502' && un.every(r => !r.note), '1.5.0: the unstake classifies with token ids from the body (no "resolve at claim" note)', un.map(r => [r.token_id, r.note])); }
  const DECLARED = (fs.readFileSync(path.join(__dirname, 'index.js'), 'utf8').match(/^\/\/ org-nft-flows (\d+\.\d+\.\d+)/m) || [])[1];   // 1.4.1: the heartbeat's version is a relation to the header, never a literal frozen in the gate
  ok(DECLARED && J('pixel-lions/nft-flows/heartbeat.json').version === DECLARED && J('pixel-lions/nft-flows/heartbeat.json').status === 'ok', `heartbeat ${DECLARED} ok (version = the header's)`);
  ok(/by-token: \d+\/\d+ shards/.test(r3.stdout), '1.4.1 by-token rebuild prints its progress line (every 20 shards and at the end)', r3.stdout.split('\n').filter(l => /by-token/.test(l)));
  ok(require('./lib/oracle-usd.js').VERSION === '1.0.0' && typeof require('./lib/oracle-usd.js').makeOracle === 'function', '1.4.1 lib/oracle-usd.js is the pricing rule (required, not copied)');
  // 1.1.4 — BBL buy-now = place_bid + settle + settle_hook in ONE tx (the exact event sequence of aDAO #745 on
  // 2026-09-12, tx C50E1FF…): the classifier read only the venue's FIRST event (place_bid), never saw the settle, and
  // filed every buy-now since 2023 as "venue release without a known verb". 317 sales missing across aDAO/PL.
  { const BLUNA = 'terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml'; const SELLER = 'terra1sellerbuynow', BUYER = 'terra1buyerbuynow';
    HEAD = 1040; blocks[1035] = { txs: ['dHg5'] }; results[1035] = [{ code: 0, events: [
      ev(BLUNA, { action: 'send', from: BUYER, to: BBL, amount: 200000000 }),
      ev(BBL,   { action: 'place_bid', auction_id: '14765', bid_amount: 200000000, bidder: BUYER, token_id: 555 }),
      ev(BBL,   { action: 'settle', auction_id: '14765', token_id: 555, denom: BLUNA, amount: 200000000, seller: SELLER }),
      ev(BLUNA, { action: 'transfer', amount: 4000000, from: BBL, to: 'terra1jgk8dhtv0qf5s08jxrwecf4a04hdmeznqpty75' }),
      ev(BLUNA, { action: 'transfer', amount: 10000000, from: BBL, to: 'terra1royaltyrecipient' }),
      ev(BLUNA, { action: 'transfer', amount: 186000000, from: BBL, to: SELLER }),
      ev(PL,    { action: 'transfer_nft', recipient: BUYER, sender: BBL, token_id: 555 }),
      ev(BBL,   { action: 'settle_hook' }),
    ] }];
    const r6 = await run(); ok(r6.status === 0 && !/FATAL/.test(r6.stdout), '1.1.4 buy-now run clean');
    const led6 = J('pixel-lions/ledger/2026/09.json'); const tx6 = led6.filter(r => r.height === 1035);
    const sale = tx6.find(r => r.kind === 'sale');
    ok(sale && sale.token_id === '555' && sale.venue === 'bbl', '1.1.4 buy-now classified as SALE #555 on bbl', tx6.map(r => r.kind + (r.note ? '(' + r.note + ')' : '')));
    ok(sale && sale.price && sale.price.amount === '200000000' && sale.price.denom === 'cw20:' + BLUNA && sale.auction_id === '14765', '1.1.4 sale price = settle amount/denom (200 bLUNA), auction_id carried', sale && [sale.price, sale.auction_id]);
    ok(sale && sale.from === SELLER && sale.to === BUYER, '1.1.4 sale from = settle seller, to = NFT recipient (buyer)', sale && [sale.from, sale.to]);
    ok(sale && sale.split && sale.split.legs && sale.split.legs.length === 3 && sale.split.legs.some(l => l.to === SELLER && l.amount === '186000000'), '1.1.4 split legs carried: fee + royalty + seller (186 of 200)', sale && sale.split);
    ok(!tx6.some(r => r.kind === 'venue_out' && /without a known verb/.test(r.note || '')), '1.1.4 no "venue release without a known verb" for a settled buy-now');
    ok(tx6.some(r => r.kind === 'bid' && r.auction_id === '14765'), '1.1.4 the place_bid leg is still recorded as bid (chain truth, same tx)'); }
  // 1.1.3 — re-price pass: two LUNA-priced sales sit in the month file with usd:null because their day was not in
  // luna-usd-daily when they were written. Day 09-11 now arrives in the series; 09-12 still has not.
  { const led4 = J('pixel-lions/ledger/2026/09.json'); const n0 = led4.length;
    led4.push({ kind: 'sale', collection: 'pixel-lions', token_id: '900', height: 990, msg_index: 0, txhash: 'SALE11', ts: '2026-09-11T10:00:00Z', price: { amount: '40000000', denom: 'uluna' }, usd: null, usd_reason: 'luna_usd_daily_missing:2026-09-11', source: 'forward:org-nft-flows' });
    led4.push({ kind: 'sale', collection: 'pixel-lions', token_id: '901', height: 991, msg_index: 0, txhash: 'SALE12', ts: '2026-09-12T10:00:00Z', price: { amount: '10000000', denom: 'uluna' }, usd: null, usd_reason: 'luna_usd_daily_missing:2026-09-12', source: 'forward:org-nft-flows' });
    put('pixel-lions/ledger/2026/09.json', led4); LUNA_DAILY['2026-09-11'] = 0.048; gh.length = 0;
    const r4 = await run(); ok(r4.status === 0 && /nothing new/.test(r4.stdout) && /repriced 1 record/.test(r4.stdout), '1.1.3 fourth run (nothing new by cursor): re-price pass still runs, 1 record', r4.stdout.split('\n').filter(l => /repriced|FATAL/.test(l)).join(' | '));
    const led5 = J('pixel-lions/ledger/2026/09.json'); const s11 = led5.find(r => r.txhash === 'SALE11'), s12 = led5.find(r => r.txhash === 'SALE12');
    ok(led5.length === n0 + 2, '1.1.3 never-shrink: record count unchanged by the re-price');
    ok(s11 && Math.abs(s11.usd - 40 * 0.048) < 1e-9 && s11.luna_usd === 0.048 && !('usd_reason' in s11) && /^\d{4}-\d{2}-\d{2}T/.test(s11.usd_repriced_at), '1.1.3 09-11 sale priced (40 LUNA × 0.048), reason removed, LABELED usd_repriced_at', s11);
    ok(s11.price.amount === '40000000' && s11.height === 990 && s11.ts === '2026-09-11T10:00:00Z', '1.1.3 event fields verbatim (only the USD derivation changed)');
    ok(s12 && s12.usd === null && /^price_history_(not_yet_written:|missing:LUNA:)2026-09-12$/.test(s12.usd_reason) && !('usd_repriced_at' in s12), '1.1.3/1.3.0 09-12 sale untouched — the oracle has not written that day yet (blank beats phantom)', s12);
    ok(gh.filter(x => x === 'PUT pixel-lions/ledger/2026/09.json').length === 1 && !gh.some(x => x.startsWith('PUT pixel-lions/raw/')), '1.1.3 exactly one month-file write, nothing else');
    ok(J('pixel-lions/nft-flows/heartbeat.json').repriced === 1, '1.1.3 heartbeat carries repriced: 1');
    // 1.2.0 — symbols from the catalog on every priced record, USD per symbol, generic reprice
    ok(led5.filter(r => r.price).every(r => 'denom_symbol' in r), '1.2.0 every priced record carries denom_symbol (stamped on the ones that predate the field)');
    ok(s11.denom_symbol === 'LUNA' && s11.denom_decimals === 6 && s11.usd_basis === 'price-history:2026-09-11 (coingecko)', '1.2.0/1.3.0 the LUNA sale says LUNA · usd_basis names the oracle day and its src');
    const dep = led5.find(r => r.kind === 'venue_deposit' && r.price && /terra1bluna$/.test(r.price.denom));
    console.log('    (deposit record: ' + JSON.stringify(dep && { denom: dep.price.denom, sym: dep.denom_symbol, reason: dep.denom_symbol_reason, usd: dep.usd, usd_reason: dep.usd_reason }) + ')');
    ok(dep && dep.denom_symbol === 'TESTLST' && dep.usd == null && /^price_history_missing:TESTLST:/.test(dep.usd_reason), '1.2.0/1.3.0 a catalog-known token the oracle does not price: symbol stamped, usd null with the reason (never a guess)');
    { const led6 = J('pixel-lions/ledger/2026/09.json');
      led6.push({ kind: 'sale', collection: 'pixel-lions', token_id: '902', height: 992, msg_index: 0, txhash: 'SALEBL', ts: '2026-09-12T10:00:00Z', price: { amount: '200000000', denom: 'cw20:terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml' }, usd: null, usd_reason: 'no_usd_series_for_denom:cw20:terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml', source: 'forward:org-nft-flows', repair: 'buy-now-settle-1.1.4' });
      led6.push({ kind: 'sale', collection: 'pixel-lions', token_id: '903', height: 993, msg_index: 0, txhash: 'SALEUS', ts: '2026-09-12T11:00:00Z', price: { amount: '15000000', denom: 'ibc/2C962DAB9F57FE0921435426AE75196009FAA1981BF86991203C8411F8980FDB' }, usd: 15, source: 'forward:org-nft-flows' });
      put('pixel-lions/ledger/2026/09.json', led6); gh.length = 0;
      const r5 = await run(); const led7 = J('pixel-lions/ledger/2026/09.json'); const bl = led7.find(r => r.txhash === 'SALEBL'), us = led7.find(r => r.txhash === 'SALEUS');
      ok(r5.status === 0 && bl && bl.denom_symbol === 'bLUNA' && Math.abs(bl.usd - 200 * 0.08) < 1e-9 && bl.usd_basis === 'price-history:2026-09-12 (coingecko)' && bl.usd_repriced_at && !bl.usd_reason && bl.repair === 'buy-now-settle-1.1.4', '1.2.0/1.3.0 a bLUNA buy-now sale written with no USD (the 1.1.4 repair rows) is USD-priced by the reprice pass from the oracle, labeled, everything else untouched', bl);
      ok(us && us.denom_symbol === 'USDC' && us.usd === 15 && !us.usd_repriced_at, '1.2.0 a stable-priced record gets its symbol stamped and its USD is left exactly as written');
      ok(J('pixel-lions/nft-flows/heartbeat.json').symbol_stamped >= 1, '1.2.0 heartbeat reports symbol_stamped');
      ok(led7.length === led6.length, '1.2.0 never-shrink through the stamp + reprice');
      // 1.2.1 — the full sweep: an OLD month listed in the ledger index (not current/previous) gets walked and priced
      const ix = J('pixel-lions/ledger/index.json'); ix.months = [...new Set([...(ix.months || []), '2024/10'])].sort(); put('pixel-lions/ledger/index.json', ix);
      put('pixel-lions/ledger/2024/10.json', [{ kind: 'sale', collection: 'pixel-lions', token_id: '77', height: 12000000, msg_index: 0, txhash: 'OLDBL', ts: '2024-10-18T22:21:00Z', price: { amount: '200000000', denom: 'cw20:terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml' }, usd: null, usd_reason: 'no_usd_series_for_denom:cw20:terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml', source: 'forward:org-nft-flows', repair: 'buy-now-settle-1.1.4' }]);
      BLUNA_DAILY['2024-10-18'] = 0.5; LUNA_DAILY['2024-10-18'] = 0.36; gh.length = 0;   // 1.3.0: the oracle carries bLUNA through the CoinGecko hole (LUNA×ratio)
      const r6 = await run(); const old = J('pixel-lions/ledger/2024/10.json')[0]; const hb6 = J('pixel-lions/nft-flows/heartbeat.json');
      ok(r6.status === 0 && old.denom_symbol === 'bLUNA' && Math.abs(old.usd - 100) < 1e-9 && old.usd_basis === 'price-history:2024-10-18 (LUNA×ratio(interpolated))' && old.usd_repriced_at, '1.2.1/1.3.0 an old month listed in the index is walked: the 2024 bLUNA repair row is priced by the oracle, the basis says the day and the oracle\'s own src', old);
      console.log("    (hb6: " + JSON.stringify({w: hb6.months_walked, t: hb6.months_touched, keys: Object.keys(hb6)}) + ")"); ok(hb6.months_walked >= 2 && (hb6.months_touched || []).includes('2024/10'), '1.2.1 heartbeat reports months_walked / months_touched', [hb6.months_walked, hb6.months_touched]);
      { const m = J('pixel-lions/ledger/2024/10.json'); m.push({ kind: 'sale', collection: 'pixel-lions', token_id: '78', height: 12000500, msg_index: 0, txhash: 'FARBL', ts: '2024-10-30T00:00:00Z', price: { amount: '100000000', denom: 'cw20:terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml' }, usd: null, usd_reason: 'no_usd_series_for_denom:cw20:terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml', source: 'forward:org-nft-flows' }); put('pixel-lions/ledger/2024/10.json', m); }
      gh.length = 0; const r6b = await run(); const far = J('pixel-lions/ledger/2024/10.json').find(r => r.txhash === 'FARBL');
      ok(r6b.status === 0 && far.usd == null && far.usd_reason === 'price_history_missing:bLUNA:2024-10-30' && far.denom_symbol === 'bLUNA', '1.3.0 a day the oracle has but not for this symbol stays null with an exact reason (never a guess)', far);
      { const m = J('pixel-lions/ledger/2024/10.json'); m.push({ kind: 'sale', collection: 'pixel-lions', token_id: '79', height: 12000600, msg_index: 0, txhash: 'COPYBL', ts: '2024-10-18T12:00:00Z', price: { amount: '100000000', denom: 'cw20:terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml' }, denom_symbol: 'bLUNA', usd: 60, usd_basis: 'bluna-usd-daily:2024-10-18', unit_usd: 0.6, source: 'forward:org-nft-flows' }); m.push({ kind: 'sale', collection: 'pixel-lions', token_id: '80', height: 12000601, msg_index: 0, txhash: 'COPYLU', ts: '2024-10-18T13:00:00Z', price: { amount: '100000000', denom: 'uluna' }, denom_symbol: 'LUNA', usd: 36, luna_usd: 0.36, usd_basis: 'luna-usd-daily:2024-10-18', source: 'forward:org-nft-flows' }); put('pixel-lions/ledger/2024/10.json', m); }
      gh.length = 0; const r6c = await run(); const cb = J('pixel-lions/ledger/2024/10.json').find(r => r.txhash === 'COPYBL'), cl = J('pixel-lions/ledger/2024/10.json').find(r => r.txhash === 'COPYLU');
      ok(r6c.status === 0 && Math.abs(cb.usd - 50) < 1e-9 && cb.usd_prev === 60 && cb.usd_prev_basis === 'bluna-usd-daily:2024-10-18' && /^price-history:2024-10-18/.test(cb.usd_basis) && cb.usd_repriced_at, '1.3.0 a bLUNA row priced from the CoinGecko copy (60) is re-priced by the oracle (50), the old number kept beside it', cb);
      ok(cl && Math.abs(cl.usd - 36) < 1e-9 && !('usd_prev' in cl) && /^price-history:2024-10-18/.test(cl.usd_basis), '1.3.0 a LUNA row priced from the copy has the same number — relabeled to the oracle, no usd_prev (a relabel is not a repair)', cl);
      gh.length = 0; const r7 = await run(); const hb7 = J('pixel-lions/nft-flows/heartbeat.json');
      ok(r7.status === 0 && (hb7.months_touched || []).length === 0 && hb7.months_walked >= 2, '1.2.1 a second sweep is a no-op: every month walked, none touched (the ledger is fully labeled)', [hb7.months_walked, hb7.months_touched]); }
    gh.length = 0; const r5 = await run(); ok(r5.status === 0 && !gh.some(x => x.startsWith('PUT pixel-lions/ledger/2026/')), '1.1.3 fifth run: nothing left to re-price, month file NOT rewritten', gh.filter(x => x.startsWith('PUT')));
    ok(J('pixel-lions/nft-flows/heartbeat.json').repriced === 0, '1.1.3 heartbeat repriced: 0 on a no-op pass'); }
  // 1.4.0 — by-token shards: the read shape for "open an NFT → its journey"
  console.log('\n== 1.4.0 by-token shards ==');
  { const bi = J('pixel-lions/ledger/by-token/index.json'); ok(bi && bi.shard_size === 100 && bi.shards['000'] && bi.shards['000'].records >= 2, 'by-token/index.json: shard_size 100, shard 000 listed with its record count');
    const s0 = J('pixel-lions/ledger/by-token/000.json'); ok(s0.tokens['42'] && s0.tokens['42'].some(r => r.kind === 'stake') && s0.tokens['77'] && s0.tokens['77'].some(r => r.kind === 'stake') && s0.range[0] === 0 && s0.range[1] === 99, 'shard 000 holds #42 and #77 with their stake records (range 0–99)', Object.keys(s0.tokens));
    const s5 = J('pixel-lions/ledger/by-token/005.json'); ok(s5 && s5.tokens['555'] && s5.tokens['555'].some(r => r.kind === 'sale' && r.price.amount === '200000000'), 'shard 005 holds the #555 buy-now sale', s5 && Object.keys(s5.tokens));
    ok(Object.values(s0.tokens).flat().every(r => !r.superseded_by), 'no superseded row in any shard');
    // a superseded row appears in the ledger → its token's shard is NOT rebuilt on a nothing-new run (nothing dirty) and never carries it
    { const m = J('pixel-lions/ledger/2024/10.json'); m.push({ kind: 'venue_out', collection: 'pixel-lions', token_id: '77', height: 12000700, msg_index: 0, txhash: 'SUPX', ts: '2024-10-31T00:00:00Z', source: 'forward:org-nft-flows', superseded_by: 'SUPX|0|sale|pixel-lions|77|-', repair: 'x' }); put('pixel-lions/ledger/2024/10.json', m); }
    gh.length = 0; const r8 = await run(); ok(r8.status === 0 && !gh.some(x => x.startsWith('PUT pixel-lions/ledger/by-token/')), 'nothing-new run with nothing dirty: no by-token shard rewritten (changed-files-only)', gh.filter(x => x.startsWith('PUT')));
    const hb8 = J('pixel-lions/nft-flows/heartbeat.json'); ok(hb8.by_token && hb8.by_token.shards_rebuilt === 0, 'heartbeat by_token: 0 shards rebuilt on a clean run', hb8.by_token);
    const env2 = Object.assign({}, env, { BY_TOKEN_ALL: '1' }); gh.length = 0;
    const r9 = await new Promise(res => { let out = ''; const p = spawn('node', ['--max-old-space-size=200', path.join(__dirname, 'index.js')], { env: env2 }); p.stdout.on('data', d => { out += d; }); p.stderr.on('data', d => { out += d; }); p.on('exit', (code) => res({ status: code, stdout: out })); });
    const hb9 = J('pixel-lions/nft-flows/heartbeat.json'); ok(r9.status === 0 && hb9.by_token && hb9.by_token.mode === 'all' && hb9.by_token.shards_rebuilt >= 2, 'BY_TOKEN_ALL=1 rebuilds every shard', hb9.by_token);
    const s0b = J('pixel-lions/ledger/by-token/000.json'); ok(!s0b.tokens['77'].some(r => r.txhash === 'SUPX') && s0b.tokens['77'].some(r => r.kind === 'stake'), 'full rebuild: the superseded venue_out of #77 is excluded, its live rows stay', s0b.tokens['77'].map(r => r.kind));
    ok(!gh.some(x => x === 'PUT pixel-lions/ledger/by-token/000.json') && r9.status === 0, 'full rebuild writes only shards whose content changed (000 unchanged → not written)', gh.filter(x => x.startsWith('PUT pixel-lions/ledger/by-token')));
  }
  // 1.5.1 — by-wallet shards: the read shape for "what did this address do / hold"
  console.log('\n== 1.5.1 by-wallet shards ==');
  { const BW = require('./lib/by-wallet.js'); const bwi = J('pixel-lions/ledger/by-wallet/index.json');
    ok(bwi && bwi.rule_version === BW.VERSION && bwi.shards && Object.keys(bwi.shards).length === 33 && Array.isArray(bwi.system_addresses) && bwi.system_addresses.includes(PLV) && bwi.system_addresses.includes(BBL), 'by-wallet/index.json: 32 bech32 shards + x, rule_version = the lib\'s, custodians and venues listed as system addresses', bwi && [bwi.rule_version, Object.keys(bwi.shards || {}).length]);
    const shMe = BW.shardOf('terra1me'), shBuyer = BW.shardOf('terra1buyerbuynow'), shSeller = BW.shardOf('terra1sellerbuynow');
    ok(shMe === 'e' && shBuyer === 'w' && shSeller === 'w', 'shard = the address\'s last character (terra1me → e, terra1buyerbuynow → w)', [shMe, shBuyer, shSeller]);
    const me = J(`pixel-lions/ledger/by-wallet/${shMe}.json`).wallets['terra1me'];
    ok(me && me.holdings_now.total === 1 && me.holdings_now.tokens[0].token_id === '42' && me.holdings_now.tokens[0].state === 'staked' && me.holdings_now.tokens[0].acquired === null && me.holdings_now.tokens[0].opened_by.kind === 'stake', 'terra1me holds #42 staked — opened by the stake the ledger saw (acquired:null, labeled, never invented)', me && me.holdings_now);
    ok(me && me.events.length === 1 && me.events[0].role === 'from' && me.events[0].kind === 'stake' && me.events[0].txhash && me.counts.stakes === 1, 'terra1me: the stake row verbatim with role:from, counts.stakes 1', me && me.counts);
    const buyer = J(`pixel-lions/ledger/by-wallet/${shBuyer}.json`).wallets['terra1buyerbuynow'], seller = J(`pixel-lions/ledger/by-wallet/${shSeller}.json`).wallets['terra1sellerbuynow'];
    ok(buyer && buyer.holdings_now.tokens.some(h => h.token_id === '555' && h.state === 'liquid' && h.acquired && h.acquired.kind === 'sale' && h.acquired.price && h.acquired.price.amount === '200000000' && h.acquired.price.symbol === 'bLUNA' && h.acquired.price.usd === null), 'buyer holds #555 liquid, acquired by the sale at 200 bLUNA (usd null: the oracle has no bLUNA for that day — blank beats phantom)', buyer && buyer.holdings_now.tokens);
    ok(buyer && buyer.counts.bought === 1 && buyer.counts.bids === 1 && buyer.events.some(e => e.kind === 'bid' && e.role === 'from'), 'buyer counts: bought 1, bids 1 (the place_bid leg is an event on the wallet, not a custody change)', buyer && buyer.counts);
    ok(seller && seller.holdings_now.total === 0 && seller.held_past.total === 1 && seller.held_past.tokens[0].token_id === '555' && seller.held_past.tokens[0].acquired === null && seller.held_past.tokens[0].released.kind === 'sale' && seller.held_past.tokens[0].pnl === undefined && /no acquisition record/.test(seller.held_past.tokens[0].note) && seller.counts.sold === 1 && seller.counts.released_without_acquisition === 1, 'seller: #555 in held_past, released by the sale, acquisition unknown (pre-ledger, labeled) → no P&L claimed', seller && seller.held_past);
    ok(!Object.keys(files).some(k => k.startsWith('pixel-lions/ledger/by-wallet/') && (J(k).wallets || {})[PLV]) && !Object.keys(files).some(k => k.startsWith('pixel-lions/ledger/by-wallet/') && (J(k).wallets || {})[BBL]), 'no shard carries a block for the voting module or the marketplace (system addresses are not wallets)');
    // P&L two ways on a full round trip inside one wallet: a LUNA buy sold in LUNA, and a LUNA buy sold in bLUNA (no LUNA-terms number)
    { const m = J('pixel-lions/ledger/2024/10.json');
      m.push({ kind: 'sale', collection: 'pixel-lions', token_id: '800', height: 12001000, msg_index: 0, txhash: 'RT1BUY', ts: '2024-10-18T01:00:00Z', venue: 'bbl', from: 'terra1someoneelse', to: 'terra1flipper', price: { amount: '100000000', denom: 'uluna' }, denom_symbol: 'LUNA', denom_decimals: 6, usd: 36, usd_basis: 'price-history:2024-10-18 (coingecko)', source: 'forward:org-nft-flows' });
      m.push({ kind: 'sale', collection: 'pixel-lions', token_id: '800', height: 12001500, msg_index: 0, txhash: 'RT1SELL', ts: '2024-10-18T05:00:00Z', venue: 'bbl', from: 'terra1flipper', to: 'terra1nextbuyer', price: { amount: '150000000', denom: 'uluna' }, denom_symbol: 'LUNA', denom_decimals: 6, usd: 54, usd_basis: 'price-history:2024-10-18 (coingecko)', source: 'forward:org-nft-flows' });
      m.push({ kind: 'sale', collection: 'pixel-lions', token_id: '801', height: 12001600, msg_index: 0, txhash: 'RT2BUY', ts: '2024-10-18T06:00:00Z', venue: 'bbl', from: 'terra1someoneelse', to: 'terra1flipper', price: { amount: '100000000', denom: 'uluna' }, denom_symbol: 'LUNA', denom_decimals: 6, usd: 36, usd_basis: 'price-history:2024-10-18 (coingecko)', source: 'forward:org-nft-flows' });
      m.push({ kind: 'sale', collection: 'pixel-lions', token_id: '801', height: 12001700, msg_index: 0, txhash: 'RT2SELL', ts: '2024-10-18T07:00:00Z', venue: 'bbl', from: 'terra1flipper', to: 'terra1nextbuyer', price: { amount: '60000000', denom: 'cw20:terra17aj4ty4sz4yhgm08na8drc0v03v2jwr3waxcqrwhajj729zhl7zqnpc0ml' }, denom_symbol: 'bLUNA', denom_decimals: 6, usd: 30, usd_basis: 'price-history:2024-10-18 (LUNA×ratio(interpolated))', source: 'forward:org-nft-flows' });
      // a superseded twin of the second sale must never enter the wallet's replay
      m.push({ kind: 'sale', collection: 'pixel-lions', token_id: '801', height: 12001700, msg_index: 0, txhash: 'RT2SELL', ts: '2024-10-18T07:00:00Z', venue: 'bbl', from: 'terra1flipper', to: 'terra1ghostbuyer', price: { amount: '60000000', denom: 'uluna' }, source: 'forward:org-nft-flows', superseded_by: 'RT2SELL|0|sale|pixel-lions|801|-' });
      put('pixel-lions/ledger/2024/10.json', m); }
    const env3 = Object.assign({}, env, { BY_WALLET_ALL: '1' }); gh.length = 0;
    const r10 = await new Promise(res => { let out = ''; const p = spawn('node', ['--max-old-space-size=200', path.join(__dirname, 'index.js')], { env: env3 }); p.stdout.on('data', d => { out += d; }); p.stderr.on('data', d => { out += d; }); p.on('exit', (code) => res({ status: code, stdout: out })); });
    const hb10 = J('pixel-lions/nft-flows/heartbeat.json'); ok(r10.status === 0 && hb10.by_wallet && hb10.by_wallet.mode === 'all' && hb10.by_wallet.shards_rebuilt === 33, 'BY_WALLET_ALL=1 rebuilds every shard (33) — heartbeat by_wallet', hb10.by_wallet);
    ok(/by-wallet: \d+\/33 shards/.test(r10.stdout), 'by-wallet rebuild prints its progress line', r10.stdout.split('\n').filter(l => /by-wallet/.test(l)));
    const fl = J(`pixel-lions/ledger/by-wallet/${BW.shardOf('terra1flipper')}.json`).wallets['terra1flipper'];
    ok(fl && fl.held_past.total === 2 && fl.realized.round_trips === 2 && fl.realized.usd.priced === 2 && fl.realized.usd.total === 12 && fl.realized.luna.priced === 1 && fl.realized.luna.total === 50, 'P&L two ways: USD (+18 − 6 = +12 over two trips), LUNA-terms only for the LUNA→LUNA trip (+50), the LUNA→bLUNA trip has no LUNA number', fl && fl.realized);
    const t801 = fl && fl.held_past.tokens.find(p => p.token_id === '801'); ok(t801 && t801.pnl.usd === -6 && t801.pnl.token === null && /bought in LUNA, sold in bLUNA/.test(t801.pnl.note) && t801.released.txhash === 'RT2SELL' && t801.released.price.symbol === 'bLUNA', '#801: USD −6, token-terms null with the reason; the superseded twin (ghost buyer) never entered', t801 && t801.pnl);
    ok(!Object.keys(files).some(k => k.startsWith('pixel-lions/ledger/by-wallet/') && (J(k).wallets || {})['terra1ghostbuyer']), 'the superseded row\'s ghost buyer has no wallet block');
    const nb = J(`pixel-lions/ledger/by-wallet/${BW.shardOf('terra1nextbuyer')}.json`).wallets['terra1nextbuyer']; ok(nb && nb.holdings_now.total === 2 && nb.holdings_now.by_state.liquid === 2, 'nextbuyer holds #800 and #801 liquid', nb && nb.holdings_now.by_state);
    gh.length = 0; const r11 = await run(); ok(r11.status === 0 && !gh.some(x => x.startsWith('PUT pixel-lions/ledger/by-wallet/')) && J('pixel-lions/nft-flows/heartbeat.json').by_wallet.shards_rebuilt === 0, 'nothing-new run with nothing dirty: no by-wallet shard rewritten (changed-files-only)', gh.filter(x => x.startsWith('PUT')));
    // a new record for terra1flipper (a transfer out of #800's buyer is unrelated) — only the shards of the record's wallets are rebuilt
    HEAD = 1050; blocks[1045] = { txs: ['dHg6'] }; results[1045] = [{ code: 0, events: [ev(PL, { action: 'transfer_nft', sender: 'terra1nextbuyer', recipient: 'terra1flipper', token_id: 800 })] }];
    gh.length = 0; const r12 = await run(); const hb12 = J('pixel-lions/nft-flows/heartbeat.json');
    const wrote = gh.filter(x => x.startsWith('PUT pixel-lions/ledger/by-wallet/')).map(x => x.split('/').pop());
    ok(r12.status === 0 && hb12.by_wallet.mode === 'dirty' && hb12.by_wallet.shards_rebuilt === new Set([BW.shardOf('terra1nextbuyer'), BW.shardOf('terra1flipper')]).size && wrote.every(f => f === 'index.json' || f === BW.shardOf('terra1nextbuyer') + '.json' || f === BW.shardOf('terra1flipper') + '.json'), 'dirty run: only the two wallets\' shards (+ index) rebuilt after a transfer', [hb12.by_wallet, wrote]);
    const fl2 = J(`pixel-lions/ledger/by-wallet/${BW.shardOf('terra1flipper')}.json`).wallets['terra1flipper'], nb2 = J(`pixel-lions/ledger/by-wallet/${BW.shardOf('terra1nextbuyer')}.json`).wallets['terra1nextbuyer'];
    // 1.5.2 — a registry change (a custodian added) rebuilds every shard on the next run, without an env toggle
    { const c2 = JSON.parse(JSON.stringify(plc)); c2.capture.custodians['terra1legacystakingv1contract000000000000000'] = { role: 'legacy_staking' }; put('pixel-lions/collection.json', c2); gh.length = 0;
      const r13 = await run(); const hb13 = J('pixel-lions/nft-flows/heartbeat.json'); const bwi2 = J('pixel-lions/ledger/by-wallet/index.json');
      ok(r13.status === 0 && hb13.by_wallet.mode === 'all (registry changed)' && hb13.by_wallet.shards_rebuilt === 33 && bwi2.system_addresses.includes('terra1legacystakingv1contract000000000000000') && /^[0-9a-f]{16}$/.test(bwi2.system_key), '1.5.2 a custodian added to the registry → every by-wallet shard rebuilt, the index carries the new system_key', hb13.by_wallet);
      gh.length = 0; const r14 = await run(); ok(r14.status === 0 && J('pixel-lions/nft-flows/heartbeat.json').by_wallet.mode === 'nothing dirty', '1.5.2 the run after that is quiet again (same registry → nothing dirty)', J('pixel-lions/nft-flows/heartbeat.json').by_wallet);
      // 1.5.3 — a holder transfers a token INTO the registry custodian: the holder keeps the position as staked:<role> (the
      // entry point must hand the custodian ROLES to the projector, not only the system set — the live 2026-09-20 miss)
      HEAD = 1060; blocks[1055] = { txs: ['dHg7'] }; results[1055] = [{ code: 0, events: [ev(PL, { action: 'transfer_nft', sender: 'terra1flipper', recipient: 'terra1legacystakingv1contract000000000000000', token_id: 800 })] }];
      gh.length = 0; const r15 = await run(); const fl3 = J(`pixel-lions/ledger/by-wallet/${BW.shardOf('terra1flipper')}.json`).wallets['terra1flipper']; const h800 = fl3 && fl3.holdings_now.tokens.find(h => h.token_id === '800');
      ok(r15.status === 0 && h800 && h800.state === 'staked:legacy_staking' && !fl3.held_past.tokens.some(p => p.token_id === '800' && p.released.txhash !== 'RT1SELL' && p.released.height === 1055), '1.5.3 a transfer into a registry custodian keeps the holder\'s position (state staked:legacy_staking), no release', fl3 && [h800, fl3.held_past.tokens.map(p => p.token_id + ':' + p.released.kind)]);
      ok(!Object.keys(files).some(k => k.startsWith('pixel-lions/ledger/by-wallet/') && (J(k).wallets || {})['terra1legacystakingv1contract000000000000000']), '1.5.3 the custodian has no wallet block');
      { const bi = J('pixel-lions/ledger/by-wallet/index.json'); bi.engine = '1.5.2'; put('pixel-lions/ledger/by-wallet/index.json', bi); gh.length = 0; const r16 = await run(); const hb16 = J('pixel-lions/nft-flows/heartbeat.json');
        ok(r16.status === 0 && hb16.by_wallet.mode === 'all (engine changed)' && hb16.by_wallet.shards_rebuilt === 33 && J('pixel-lions/ledger/by-wallet/index.json').engine === hb16.version, '1.5.3 an index built by an older engine → every shard rebuilt once, index stamped with the running engine', hb16.by_wallet); }
      put('pixel-lions/collection.json', plc); }
    ok(fl2 && fl2.holdings_now.tokens.some(h => h.token_id === '800' && h.acquired.kind === 'transfer') && nb2 && nb2.holdings_now.total === 1 && nb2.held_past.tokens.some(p => p.token_id === '800' && p.released.kind === 'transfer' && p.pnl === undefined), 'after the transfer: flipper holds #800 again (acquired by transfer), nextbuyer\'s #800 closed by the transfer with no P&L (not a sale)');
  }
  ok(LUNA_HITS.length === 0 && ORACLE_HITS.length >= 1 && ORACLE_HITS.every(p => /\/price-history\/\d{4}\/\d{2}\.json$/.test(p)), '1.3.0: prices come ONLY from the org oracle price-history/YYYY/MM.json (no per-collection usd-daily read at all) — ' + JSON.stringify([...new Set(LUNA_HITS)]));
  ok(!J('pixel-lions/nft-flows/heartbeat.json').errors.some(e => /usd-daily|price-history/.test(e)), '1.1.2/1.3.0: no price-source error in the heartbeat');
  ghs.close(); rpc.close(); console.log(`\n${pass}/${pass + fail} passed`); process.exit(fail ? 1 : 0);
})();
